[2024-09-13T15:07:23.462+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: covid_data_ingestion_dag.ingest_covid_data scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-13T15:07:23.483+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: covid_data_ingestion_dag.ingest_covid_data scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-13T15:07:23.483+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T15:07:23.484+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-13T15:07:23.485+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T15:07:23.523+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ingest_covid_data> on 2024-09-12 00:00:00+00:00
[2024-09-13T15:07:23.536+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid_data_ingestion_dag', 'ingest_covid_data', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpjkz0we7p']
[2024-09-13T15:07:23.538+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask ingest_covid_data
[2024-09-13T15:07:23.536+0000] {standard_task_runner.py:55} INFO - Started process 181 to run task
[2024-09-13T15:07:23.560+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-13T15:07:23.583+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:121 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-13T15:07:23.631+0000] {task_command.py:389} INFO - Running <TaskInstance: covid_data_ingestion_dag.ingest_covid_data scheduled__2024-09-12T00:00:00+00:00 [running]> on host 94e336337df0
[2024-09-13T15:07:23.725+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_data_ingestion_dag
AIRFLOW_CTX_TASK_ID=ingest_covid_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-12T00:00:00+00:00
[2024-09-13T15:07:23.911+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052 InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2024-09-13T15:07:24.963+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-09-13T15:07:24.971+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=covid_data_ingestion_dag, task_id=ingest_covid_data, execution_date=20240912T000000, start_date=20240913T150723, end_date=20240913T150724
[2024-09-13T15:07:25.003+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-13T15:07:25.027+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
